# Generated by Django 4.2.2 on 2023-06-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('french', 'French'), ('italian', 'Italian'), ('indian', 'Indian'), ('ghanaian', 'Ghanian')], max_length=100)),
                ('diet', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten-free', 'Gluten-Free'), ('dairy-free', 'Dairy-Free')], max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=100)),
                ('time', models.DurationField()),
                ('food_image', models.ImageField(upload_to='food/images')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
