# Generated by Django 4.2.2 on 2023-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='diet',
            new_name='diet_type',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='category',
        ),
        migrations.AddField(
            model_name='recipes',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('supper', 'Supper'), ('dessert', 'Dessert')], default='', max_length=100),
        ),
    ]
