# Generated by Django 4.2.2 on 2023-06-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='chef',
        ),
    ]
