# Generated by Django 4.2.2 on 2023-06-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_user_like_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='chef',
            new_name='user',
        ),
    ]
